### PR TITLE
New idea form validation

### PR DESCRIPTION
**Pull request by alexbeletsky**
Put the validation code that prevents submittion of the form in case of Title / Descriptions are empty.

### CODE REVIEW

**Comment by alexbeletsky** [comment]
Added server side validation as well

**Comment by alexbeletsky** [comment]
Same verification code added then user editing an Idea;

**Comment by ghost** [comment]
Can you pull latest into your branch/fork so its easier for us to merge it in?

**Comment by alexbeletsky** [comment]
will do

**Comment by alexbeletsky** [comment]
done

**Comment by alexbeletsky** [comment]
Done

**Pull request merged**
