### PR TITLE
Cleanup code and delete comment 

### PR DESCRIPTION
**Pull request by rodrigovidal**

### CODE REVIEW

**Comment by rodrigovidal** [comment]
Anyone?

**Comment by shiftkey** [comment]
@rodrigovidal On hold while @jongalloway is refactoring the repository layer to leverage generics

**Comment by shiftkey** [comment]
On the changes: I don't like having the repository throw an exception for the cases outlined, as it requires the modules logic to do one of two things:
- wrap calls in try-catch blocks and handle exceptions (more code), or
- let the exception bubble up and give the user a 500 page (bad experience)

Do we need this code? The repository classes have been greatly simplified yesterday, and I'd rather focus on the front-end code initially rather than backend code.

**Comment by rodrigovidal** [comment]
How will you deal with the possible NullReferenceException?

**Comment by shiftkey** [comment]
The NullReferenceException on the Idea class or on the related entity - Features/Activities/Votes?

**Comment by rodrigovidal** [comment]
Where I threw the exception.

**Comment by shiftkey** [comment]
I prefer the original behaviour of returning a value to indicate to the caller that it was not successful.

Throwing an exception at this point seems like overkill for what we're doing.

**Comment by rodrigovidal** [comment]
So, do it. I disagree :) But no problem!

**Pull request closed without merging**
