### PR TITLE
Added contra code to home page

### PR DESCRIPTION
**Pull request by jongalloway**
up up down down left right left right ba enter (corrected)

### CODE REVIEW

**Comment by jongalloway** [comment]
By the way - not offended at all if you think this doesn't fit in. It shouldn't affect performance at all, but doesn't add anything useful.

**Comment by shiftkey** [comment]
To think that I spent a good ten minutes following the instructions diligently instead of listening to my inner child scream "IT'S B THEN A, GALLOWAY. DON'T MAKE ME SEND YOU A NES TO PROVE A POINT"

Anyway, fun times.

**Comment by jongalloway** [comment]
Ha - that's what I get for submitting this late at night. I think the code was right, just not the PR comment.

**Comment by shiftkey** [comment]
_thumbs up_

**Pull request merged**
